version: '3'

services: 
  marketplace:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'japan'
    restart: always
    volumes:
      - japan-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: japanuser
      POSTGRES_PASSWORD: japanuser123

volumes:
  japan-data:
